workflow:
  hindcast: true
  forecast: false

parameters:
  month: 5
  leads: "2,3,4"
  area: "39,60,-11,141"
  variable: "total_precipitation"
  location: "None"
  method: "pmesh"
  pycpt: true
  predictor_area: "40,0,-40,359"
  forecast_year: 2025

paths:
  base: "./output/single_script"
  logdir: "{base}/logfiles"
  hindcast:
    downloads: "{base}/hindcast/downloads"
    products: "{base}/hindcast/products"
    scores: "{base}/hindcast/scores"
    plots: "{base}/hindcast/plots"
    pycpt: "{base}/hindcast/pycpt"
  forecast:
    downloads: "{base}/forecast/downloads"
    products: "{base}/forecast/products"
    scores: "{base}/forecast/scores"
    plots: "{base}/forecast/plots"
    pycpt: "{base}/forecast/pycpt"

centres:
  - meteo_france
  - dwd
  - cmcc
  - ncep
  - ukmo
  - ecmwf
  - jma
  - eccc
  - bom
  - mme

services:
  ecmwf: [51, 1]
  meteo_france: [9, 1]
  dwd: [22, 1]
  cmcc: [35, 1]
  ncep: [2, 1]
  jma: [3, 0]
  eccc_can: [4, 1]
  eccc_gem5: [5, 1]
  ukmo: [604, 1]
  bom: [2, 1]
  mme: [1, 0]
