name: osop
channels:
  - iri-nextgen
  - conda-forge
dependencies:
  - pycpt
  - cptdl
  - xarray-regrid
  - xarray
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - requests
  - packaging
  - python-dateutil
  - pyyaml
  - python-eccodes
  - rioxarray 
  - cfgrib
  - cdsapi
  - xskillscore
  - pytest
  - pytest-cov
  - black
  - sphinx
  - myst-parser
  - pre-commit
  - ruff