name: osop
channels:
  - iri-nextgen
  - conda-forge
dependencies:
  - pycpt
  - xarray-regrid
  - cfgrib
  - cdsapi
  - xskillscore
  - pytest
  - pytest-cov
  - black
  - sphinx
  - myst-parser
  - pre-commit
  - ruff